# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.compiled_pb import auth_pb2 as auth__pb2

class AuthStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
            '/auth.Auth/Login',
            request_serializer=auth__pb2.LoginRequest.SerializeToString,
            response_deserializer=auth__pb2.TokenReply.FromString,
        )
        self.Refresh = channel.unary_unary(
            '/auth.Auth/Refresh',
            request_serializer=auth__pb2.RefreshToken.SerializeToString,
            response_deserializer=auth__pb2.TokenReply.FromString,
        )
        self.Logout = channel.unary_unary(
            '/auth.Auth/Logout',
            request_serializer=auth__pb2.RefreshToken.SerializeToString,
            response_deserializer=auth__pb2.LogoutReply.FromString,
        )
        self.SayHello = channel.unary_unary(
            '/auth.Auth/SayHello',
            request_serializer=auth__pb2.HelloRequest.SerializeToString,
            response_deserializer=auth__pb2.HelloReply.FromString,
        )


class AuthServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Refresh(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Login': grpc.unary_unary_rpc_method_handler(
            servicer.Login,
            request_deserializer=auth__pb2.LoginRequest.FromString,
            response_serializer=auth__pb2.TokenReply.SerializeToString,
        ),
        'Refresh': grpc.unary_unary_rpc_method_handler(
            servicer.Refresh,
            request_deserializer=auth__pb2.RefreshToken.FromString,
            response_serializer=auth__pb2.TokenReply.SerializeToString,
        ),
        'Logout': grpc.unary_unary_rpc_method_handler(
            servicer.Logout,
            request_deserializer=auth__pb2.RefreshToken.FromString,
            response_serializer=auth__pb2.LogoutReply.SerializeToString,
        ),
        'SayHello': grpc.unary_unary_rpc_method_handler(
            servicer.SayHello,
            request_deserializer=auth__pb2.HelloRequest.FromString,
            response_serializer=auth__pb2.HelloReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'auth.Auth', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Auth(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
              target,
              options=(),
              channel_credentials=None,
              call_credentials=None,
              insecure=False,
              compression=None,
              wait_for_ready=None,
              timeout=None,
              metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.Auth/Login',
                                             auth__pb2.LoginRequest.SerializeToString,
                                             auth__pb2.TokenReply.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Refresh(request,
                target,
                options=(),
                channel_credentials=None,
                call_credentials=None,
                insecure=False,
                compression=None,
                wait_for_ready=None,
                timeout=None,
                metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.Auth/Refresh',
                                             auth__pb2.RefreshToken.SerializeToString,
                                             auth__pb2.TokenReply.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Logout(request,
               target,
               options=(),
               channel_credentials=None,
               call_credentials=None,
               insecure=False,
               compression=None,
               wait_for_ready=None,
               timeout=None,
               metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.Auth/Logout',
                                             auth__pb2.RefreshToken.SerializeToString,
                                             auth__pb2.LogoutReply.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHello(request,
                 target,
                 options=(),
                 channel_credentials=None,
                 call_credentials=None,
                 insecure=False,
                 compression=None,
                 wait_for_ready=None,
                 timeout=None,
                 metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.Auth/SayHello',
                                             auth__pb2.HelloRequest.SerializeToString,
                                             auth__pb2.HelloReply.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
