# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"/\n\nTokenReply\x12\r\n\x05token\x18\x01 \x01(\t\x12\x12\n\ntoken_type\x18\x02 \x01(\t\"%\n\x0cRefreshToken\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"\x1e\n\x0bLogoutReply\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xd1\x01\n\x04\x41uth\x12/\n\x05Login\x12\x12.auth.LoginRequest\x1a\x10.auth.TokenReply\"\x00\x12\x31\n\x07Refresh\x12\x12.auth.RefreshToken\x1a\x10.auth.TokenReply\"\x00\x12\x31\n\x06Logout\x12\x12.auth.RefreshToken\x1a\x11.auth.LogoutReply\"\x00\x12\x32\n\x08SayHello\x12\x12.auth.HelloRequest\x1a\x10.auth.HelloReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGINREQUEST._serialized_start=20
  _LOGINREQUEST._serialized_end=70
  _TOKENREPLY._serialized_start=72
  _TOKENREPLY._serialized_end=119
  _REFRESHTOKEN._serialized_start=121
  _REFRESHTOKEN._serialized_end=158
  _LOGOUTREPLY._serialized_start=160
  _LOGOUTREPLY._serialized_end=190
  _HELLOREQUEST._serialized_start=192
  _HELLOREQUEST._serialized_end=220
  _HELLOREPLY._serialized_start=222
  _HELLOREPLY._serialized_end=251
  _AUTH._serialized_start=254
  _AUTH._serialized_end=463
# @@protoc_insertion_point(module_scope)
